name: Distribution Worflow
on:
  push:
    branches:
      - "main"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish-on-npm:
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.setPublished.outputs.published }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "pnpm"

      # We install all the dependencies
      - run: pnpm install --frozen-lockfile
      
      # We check whether we have a changeset or not
      #
      # If there is no changeset, then it means that it is an ordinary commit
      # and the action simply runs `pnpm distribute`
      # and because, the package version remains same in the commit,
      # so npm will not publish this new commit 
      # (good for commit types like refactor:)
      #
      # However, if there is a changeset, then it means the version needs to be bumped up.
      # So, changeset will create a PR to update the changelog and the version.
      #
      # After we accept the PR, we will have a new commit,
      # without a changeset, which will cause this new commit to through `pnpm distribute`
      # and because this time the version has been updated so, npm will publish it :)
      - name: Changeset - Either create a pull request or publish on npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm distribute
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Post Publish
        id: setPublished
        if: steps.changesets.outputs.published == 'true'
        run: echo "published=true" >> $GITHUB_OUTPUT

  publish-on-github-packages:
    needs: [publish-on-npm]
    runs-on: ubuntu-latest
    # If package was published on npm, we publish it on GitHub Packages
    if: needs.publish-on-npm.outputs.published == 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "pnpm"
          # We set registry to GitHub Packages
          registry-url: https://npm.pkg.github.com/

      # We install all the dependencies
      - run: pnpm install --frozen-lockfile
      - name: Publish on GitHub packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
